[manifest]
version = "1.0.0"
priority = 2147483600

[[patches]]
[patches.pattern]
target = 'card.lua'
match_indent = true
pattern = '''
if self.ability.consumeable or self.ability.set == 'Joker' then
'''
position = 'before'
payload = '''
trigger_extra_buttons(self, is_higlighted)
'''
times = 1








